development:
  adapter: postgresql
  encoding: unicode
  database: consumer_development
  pool: 5
  username: daimler456
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: consumer_test
  pool: 5
  username: daimler456
  password:
